apiVersion: apps/v1
kind: Deployment
metadata:
    name: petclinic-deployment
    labels:
       app: petclinic-app
spec:
  replicas: 3
  selector:
   matchLabels:
     app: petclinic-app
  template:
   metadata:
     labels:
       app: petclinic-app
   spec:
     containers:
     - name: petclinic
       image: manojd123/petclinicprivate
       ports:
        - containerPort: 80
     imagePullSecrets:
        - name: regcred
        

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
   type: NodePort
   selector:
       app: petclinic-app
   ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

